
version: '3.0'

services:
  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./wait-for:/usr/local/bin/wait-for
    command: ["/usr/local/bin/wait-for", "node:3000", "--", "nginx", "-g", "daemon off;"]
    container_name: nginx
    ports:
      - 80:80
    tty: true
    networks:    
      - desafionet
  node:
    build:
      context: ./src/
      dockerfile: Dockerfile
    image: soterogabriel/nodefullcycle
    container_name: node    
    tty: true
    expose:
      - 3000
    volumes:
      - ./src:/src
      - /src/node_modules
      - ./wait-for:/usr/local/bin/wait-for
    command: ["/usr/local/bin/wait-for", "db:3306", "--", "npm", "start"]
    networks:
      - desafionet
    depends_on:
      - db    
  db:
    image: mysql:latest
    command: 
      - mysqld
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle      
    tty: true
    ports:
      - "3306:3306"
    networks:
      - desafionet
networks:
  desafionet:
    driver: bridge

